### ISSUE TITLE
Intermittent: Null Pointer Exception when setting adapter second time with updated list

### ISSUE THREAD

**Issue by mdrafiwynk** [rubensousa/DpadRecyclerView#288] opened 2024-11-15 08:30 UTC
Fatal Exception: java.lang.NullPointerException
Attempt to invoke virtual method 'void android.view.View.clearAccessibilityFocus()' on a null object reference

Stack Trace : 

 Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.clearAccessibilityFocus()' on a null object reference
       at android.view.ViewGroup.removeViewInternal(ViewGroup.java:5594)
       at android.view.ViewGroup.removeViewAt(ViewGroup.java:5550)
       at com.rubensousa.dpadrecyclerview.DpadRecyclerView.removeViewAt(DpadRecyclerView.kt:367)
       at androidx.recyclerview.widget.RecyclerView$5.removeViewAt(RecyclerView.java:915)
       at androidx.recyclerview.widget.ChildHelper.removeViewAt(ChildHelper.java:168)
       at androidx.recyclerview.widget.RecyclerView$LayoutManager.removeViewAt(RecyclerView.java:8940)
       at androidx.recyclerview.widget.RecyclerView$LayoutManager.removeAndRecycleViewAt(RecyclerView.java:9211)
       at androidx.recyclerview.widget.RecyclerView$LayoutManager.removeAndRecycleAllViews(RecyclerView.java:10624)
       at androidx.recyclerview.widget.RecyclerView.removeAndRecycleViews(RecyclerView.java:1212)
       at androidx.recyclerview.widget.RecyclerView.setAdapterInternal(RecyclerView.java:1236)
       at androidx.recyclerview.widget.RecyclerView.setAdapter(RecyclerView.java:1194)
       at tv.airtel.xstream.adapters.ContentListAdapter$ContentListViewHolder.bindItem(ContentListAdapter.kt:618)
       at tv.airtel.xstream.adapters.ContentListAdapter.onBindViewHolder(ContentListAdapter.kt:197)
       at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:7254)
       at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:7337)
       at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:6194)
       at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6460)
       at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6300)
       at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6296)
       at com.rubensousa.dpadrecyclerview.layoutmanager.layout.linear.LinearLayoutEngineer.initLayout(LinearLayoutEngineer.kt:63)
       at com.rubensousa.dpadrecyclerview.layoutmanager.layout.StructureEngineer.layoutChildren(StructureEngineer.kt:205)
       at com.rubensousa.dpadrecyclerview.layoutmanager.layout.PivotLayout.layoutChildren(PivotLayout.kt:124)
       at com.rubensousa.dpadrecyclerview.layoutmanager.layout.PivotLayout.onLayoutChildren(PivotLayout.kt:89)
       at com.rubensousa.dpadrecyclerview.layoutmanager.PivotLayoutManager.onLayoutChildren(PivotLayoutManager.kt:129)
       at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4309)
       at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:4012)
       at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4578)
       at android.view.View.layout(View.java:24421)
       at android.view.ViewGroup.layout(ViewGroup.java:6443)
       at androidx.constraintlayout.widget.ConstraintLayout.onLayout(ConstraintLayout.java:1915)
       at android.view.View.layout(View.java:24421)
       at android.view.ViewGroup.layout(ViewGroup.java:6443)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
       at android.view.View.layout(View.java:24421)
       at android.view.ViewGroup.layout(ViewGroup.java:6443)
       at androidx.constraintlayout.widget.ConstraintLayout.onLayout(ConstraintLayout.java:1915)
       at android.view.View.layout(View.java:24421)
       at android.view.ViewGroup.layout(ViewGroup.java:6443)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
       at android.view.View.layout(View.java:24421)
       at android.view.ViewGroup.layout(ViewGroup.java:6443)
       at androidx.constraintlayout.widget.ConstraintLayout.onLayout(ConstraintLayout.java:1915)
       at android.view.View.layout(View.java:24421)
       at android.view.ViewGroup.layout(ViewGroup.java:6443)
       at androidx.constraintlayout.widget.ConstraintLayout.onLayout(ConstraintLayout.java:1915)
       at android.view.View.layout(View.java:24421)
       at android.view.ViewGroup.layout(ViewGroup.java:6443)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
       at android.view.View.layout(View.java:24421)
       at android.view.ViewGroup.layout(ViewGroup.java:6443)
       at androidx.constraintlayout.widget.ConstraintLayout.onLayout(ConstraintLayout.java:1915)
       at android.view.View.layout(View.java:24421)
       at android.view.ViewGroup.layout(ViewGroup.java:6443)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
       at android.view.View.layout(View.java:24421)
       at android.view.ViewGroup.layout(ViewGroup.java:6443)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1891)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1729)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1638)
       at android.view.View.layout(View.java:24421)
       at android.view.ViewGroup.layout(ViewGroup.java:6443)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
       at com.android.internal.policy.DecorView.onLayout(DecorView.java:789)
       at android.view.View.layout(View.java:24421)
       at android.view.ViewGroup.layout(ViewGroup.java:6443)
       at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:4258)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3583)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2465)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9305)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1339)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1348)
       at android.view.Choreographer.doCallbacks(Choreographer.java:952)
       at android.view.Choreographer.doFrame(Choreographer.java:882)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1322)
       at android.os.Handler.handleCallback(Handler.java:958)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:205)
       at android.os.Looper.loop(Looper.java:294)
       at android.app.ActivityThread.main(ActivityThread.java:8177)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)

**Comment by rubensousa** [comment] 2024-11-15 10:01
@mdrafiwynk 

Can you explain what you mean with setting adapter second time? Please show me a small code example that triggers this crash

**Comment by rubensousa** [comment] 2024-11-15 12:02
@mdrafiwynk 

But can you show me how you trigger those updates exactly? It's important for me to check how you're triggering the updates so I can reproduce the issue myself

**Comment by rubensousa** [comment] 2024-11-15 12:03
So you're using `setAdapter` multiple times, is that it?

**Comment by mdrafiwynk** [comment] 2024-11-15 13:25
Yes. I am using nested recyler view and inside each parent recycler view nested recyler view adapter is called every time when anything added or removed in rail. Ex - Continue watching rail

**Comment by rubensousa** [comment] 2024-11-15 15:53
Can you please share a small demo project with those `setAdapter` calls then?

**Comment by rubensousa** [comment] 2024-11-20 21:06
@mdrafiwynk any update here?

**Comment by mdrafiwynk** [comment] 2024-11-21 03:43
Sorry. But i didn't have time to create demo. Also I am not sure this is the Rott cause for this or not. But this is very frequently observed when use nested recyler view

**Comment by rubensousa** [comment] 2024-12-08 19:27
@mdrafiwynk closing since there's no sample that reproduces the issue

**Closed by rubensousa** 2024-12-08 19:27 UTC
