### ISSUE TITLE
Not able to scroll down or up on some particular view types

### ISSUE THREAD

**Issue by mdrafiwynk** [rubensousa/DpadRecyclerView#272] opened 2024-10-04 18:56 UTC
I am using version `1.2.0-alpha03` version of library. I am using different view types in reycler view where card have different sizes. But in some screen sizes or some view type order. I am not able to scroll down or up on Dpad -down or up click. I am getting stuck on some rails (calling horizontal row). My first rail is Apps rail and second is MyWatchlist. But I am not able to go to apps to watchlist on dpad-down click but able to go to feature banner. Please check the below video for reference and let me know the RCA for this. I have reproduce this by changing the screen size 1920*1080 to 1080*1920. As its not happing for all screen sizes. I think this might be some alignment issue. 

Screen size : 1080x1920 (Not working)
[Screen_recording_20241005_002559.webm](https://github.com/user-attachments/assets/1af0752e-329b-4a72-8736-d43f7233a3ab)

Screen size : 1920x1080 (Working fine)
[Screen_recording_20241005_003353.webm](https://github.com/user-attachments/assets/266cdd38-1e14-4515-8d12-a9048e387249)

Please help me to get rid of this issue @rubensousa

**Comment by rubensousa** [comment] 2024-10-05 15:21
@mdrafiwynk please check if that issue is reproducible with the latest alpha version `1.4.0-alpha06`.  If it is, I would need a code sample to investigate it, since I can't reproduce this in the sample project here in the repo

**Comment by mdrafiwynk** [comment] 2024-10-05 15:26
Yes its also exist in latest version. You can reproduce it by decreasing screen size like 1080x1920. Just add view type with landscape card and then portrait card as i did. I don't have sample. I have real project that I can't share with you due to company policy. I am having rely on your library. 


I have tried to debug and but not able to debug much due to code complexity.

**Comment by rubensousa** [comment] 2024-10-05 15:42
@mdrafiwynk can you please fork this project and modify the sample so that the issue is clearly reproducible there? I can launch the sample in my phone and it still behaves correctly.

**Comment by mdrafiwynk** [comment] 2024-10-05 15:43
> @mdrafiwynk can you please fork this project and modify the sample so that the issue is clearly reproducible there? I can launch the sample in my phone and it still behaves correctly.

Sure. I will

**Comment by rubensousa** [comment] 2024-10-05 15:44
> Could you please give urgent attention to this if possible

I work on this in my free time. If you need urgent help, I would advise you to provide a sample that reproduces the issue. I'm currently preparing the next beta version and could have a look at that issue if you show me that it is reproducible in the latest state

**Comment by mdrafiwynk** [comment] 2024-10-07 06:57
> > Could you please give urgent attention to this if possible
> 
> I work on this in my free time. If you need urgent help, I would advise you to provide a sample that reproduces the issue. I'm currently preparing the next beta version and could have a look at that issue if you show me that it is reproducible in the latest state

@rubensousa I found the exact issue. Actually. I have one case in which I have rail title came from API but I have to fetch horizontal list from db. Like in case of continue watching rail from API I got only title and then I add that rail into the adapter list without its content and when it fetch from db I search the rail and update its horizontal list. But I got empty list from db then I also don't show the title but item exist in adpter but there is no card visible. I that case focus is not moving to next visible card.

**Comment by rubensousa** [comment] 2024-10-07 08:03
@mdrafiwynk Please provide a sample that showcases that issue. I can't help without seeing what's happening

**Comment by mdrafiwynk** [comment] 2024-10-07 20:44
> @mdrafiwynk Please provide a sample that showcases that issue. I can't help without seeing what's happening

Give me some time. I'll provide the same

**Comment by rubensousa** [comment] 2024-10-08 17:55
I'm closing this since this is related to https://github.com/rubensousa/DpadRecyclerView/issues/274

The root cause seems to be the same. Feel free to re-open if it's not fixed in the latest snapshot

**Comment by mdrafiwynk** [comment] 2024-10-08 18:58
Its not fixed.. I have checked with latest fix but this issue still persist. I will share one sample tomorrow for reproduction.

**Comment by rubensousa** [comment] 2024-10-08 21:34
I managed to reproduce this only when `setFocusSearchDisabled` is used: https://github.com/rubensousa/DpadRecyclerView/pull/278/files

All other cases, including when a DpadRecyclerView is empty, seem to be fine. I will check your sample once you share it

**Comment by rubensousa** [comment] 2024-10-10 13:25
@mdrafiwynk any update here?

**Comment by rubensousa** [comment] 2024-10-14 19:49
@mdrafiwynk did you have time to check this again?

**Comment by mdrafiwynk** [comment] 2024-10-14 20:30
@rubensousa Sorry for late reply. But I didn't get time to create sample for this. I will try to do this on weekend.

**Comment by rubensousa** [comment] 2024-10-22 22:31
@mdrafiwynk Any update here?

**Comment by rubensousa** [comment] 2024-10-29 21:22
@mdrafiwynk I'm going to close this since there are no more updates

**Closed by rubensousa** 2024-10-29 21:22 UTC
Labels: bug, question
