### ISSUE TITLE
support paging

### ISSUE THREAD

**Issue by liyuzheng** [rubensousa/DpadRecyclerView#114] opened 2023-03-30 04:28 UTC
when use paging ,hold down button,it's was crash
java.lang.IllegalArgumentException: Required value was null.
                                                                                                    	at com.rubensousa.dpadrecyclerview.layoutmanager.layout.grid.GridLayoutEngineer.layoutPivotRow(GridLayoutEngineer.kt:145)
                                                                                                    	at com.rubensousa.dpadrecyclerview.layoutmanager.layout.grid.GridLayoutEngineer.initLayout(GridLayoutEngineer.kt:103)
                                                                                                    	at com.rubensousa.dpadrecyclerview.layoutmanager.layout.StructureEngineer.layoutChildren(StructureEngineer.kt:200)
                                                                                                    	at com.rubensousa.dpadrecyclerview.layoutmanager.layout.PivotLayout.layoutChildren(PivotLayout.kt:116)
                                                                                                    	at com.rubensousa.dpadrecyclerview.layoutmanager.layout.PivotLayout.onLayoutChildren(PivotLayout.kt:85)
                                                                                                    	at com.rubensousa.dpadrecyclerview.layoutmanager.PivotLayoutManager.onLayoutChildren(PivotLayoutManager.kt:125)

 private fun setupRv() {
        val rv = mBinding.rv
        rv.apply {
            adapter = this@CategoryFragment.adapter
            itemAnimator = null
            setSpanCount(5)
            addItemDecoration(
                DpadGridSpacingDecoration.create(
                    itemSpacing = 20.dp
                ).also {
                    it.setSpacingLookup(object : DpadSpacingLookup {
                        override fun shouldApplySpacing(
                            viewHolder: RecyclerView.ViewHolder,
                            itemCount: Int
                        ): Boolean {
                            return viewHolder.absoluteAdapterPosition > 0
                        }
                    })
                }
            )
        }
    }

    override fun setupData() {
        super.setupData()
        lifecycleScope.launchWhenResumed {
           //Flow<PagingData<*>>
            categoryFragmentVM.fetch().collectLatest {
                adapter.submitData(it)
            }
        }
    }

class ItemAdapter :
    PagingDataAdapter<CategoryDetails, ItemAdapter.ItemHolder>(CategoryDetails.diffCallback) {

    class ItemHolder(view: View) : RecyclerView.ViewHolder(view) {
        fun bind(data: CategoryDetails) {
            val img = itemView.findViewById<ImageView>(R.id.img1)
            img.run {
                Glide.with(this)
                    .asBitmap()
                    .centerCrop()
                    .load(data.imgSrc)
                    .into(this)
            }
            val txt = itemView.findViewById<TextView>(R.id.txt)
            txt.text = data.id.toString()
        }
    }

    override fun onBindViewHolder(holder: ItemHolder, position: Int) {
        val item = getItem(position) ?: return
        holder.bind(item)
    }

    override fun onCreateViewHolder(parent: ViewGroup, viewType: Int): ItemHolder {
        val view = LayoutInflater.from(parent.context)
            .inflate(R.layout.item_big, parent, false)
        return ItemHolder(view)
    }
}

**Comment by liyuzheng** [comment] 2023-03-30 06:51
if use 
val DEFAULT_PAGER = PagingConfig(
    pageSize = 20,
    initialLoadSize = 60,
    prefetchDistance = 10,
    enablePlaceholders = true   //true   it's all right     false  crash
)

**Comment by rubensousa** [comment] 2023-04-02 16:46
Thanks for the bug report. Can you please update this sample to a repo here in github?

**Comment by rubensousa** [comment] 2023-04-02 17:49
@liyuzheng I created this branch to try to reproduce the crash, but I still couldn't. Can you please check it out? https://github.com/rubensousa/DpadRecyclerView/tree/bugfix/paging_crash

There's a `GridPagingFragment` and a `GridPagingViewModel`

**Comment by rubensousa** [comment] 2023-04-02 22:00
Fix should be there in 1.0.0-beta01 now. Please try it out. In case you have any other issues, please file a PR targeting changes in `GridPagingFragment` or `GridPagingViewModel` that reproduce them

**Comment by liyuzheng** [comment] 2023-04-12 03:19
I'm sorry my English is bad.  I'll try it and write the code here .  thank you.

**Comment by liyuzheng** [comment] 2023-04-12 06:28
```
Adapter : PagingDataAdapter{
  open fun getItemViewType(position: Int, data: T?): Int = 0
  final override fun getItemViewType(position: Int): Int {
          try {
              //It's my problem,
              //getItem(position) here caused a crash  when PagingConfig disable placeholder
              val data = getItem(position) ?: return getItemViewType(position, null)
              return getItemViewType(position, data)
          } catch (ex: Exception) {
              return getItemViewType(position, null)
          }
      }
  }
```

**Comment by liyuzheng** [comment] 2023-04-12 06:31
Thanks again @rubensousa

**Comment by rubensousa** [comment] 2023-04-12 16:41
@liyuzheng is that another issue? If so, please create another bug ticket and try to file a MR with this exact code in the same fragment I shared last time: GridPagingFragment

**Comment by liyuzheng** [comment] 2023-04-13 02:00
> @liyuzheng那是另一个问题吗？如果是这样，请创建另一个错误票并尝试在我上次共享的同一片段中使用此确切代码提交 PR：GridPagingFragment

No,it's the same problem.I didn't describe it clearly before,It's a problem of usage,Paging can't use getItem(position) in  fun getItemViewType(position:Int).

**Comment by liyuzheng** [comment] 2023-04-13 02:02
No,it's the same problem.I didn't describe it clearly before,It's a problem of usage,Paging can't use getItem(position) in fun getItemViewType(position:Int) when PagingConfig(placeholder = false)

**Comment by rubensousa** [comment] 2023-04-13 19:10
Did you update to the latest version? `1.0.0-beta01` ? 
If so, please share the latest stacktrace and try to reproduce that bug in the official sample here. I can't help without knowing the complete sample where you see this problem

**Comment by rubensousa** [comment] 2023-04-17 01:06
@liyuzheng after rechecking your comments, this seems like a problem with the Paging library and not really because of this library? I will close this, let me know if there's anything else I'm missing

**Closed by rubensousa** 2023-04-17 01:06 UTC
Labels: bug
